#!/bin/bash
export StartupDelay=0

# /insilications/build/custom-apps/VirtualBiosMod/tools/uefi-run --bios /insilications/build/custom-apps/VirtualBiosMod/tools/OVMF.fd --qemu qemu-system-x86_64 /insilications/build/custom-apps/VirtualBiosMod/VirtualBiosMod.efi

# /insilications/build/custom-apps/VirtualBiosMod/tools/uefi-run --bios /insilications/build/custom-apps/VirtualBiosMod/OVMF.fd --qemu qemu-system-x86_64 /insilications/build/custom-apps/VirtualBiosMod/VirtualBiosMod.efi

# /insilications/build/custom-apps/VirtualBiosMod/tools/uefi-run /insilications/build/custom-apps/VirtualBiosMod/VirtualBiosMod.efi --bios /insilications/build/custom-apps/VirtualBiosMod/OVMF.fd --qemu qemu-system-x86_64 -- -enable-kvm -smp 6 -cpu host -m 4024 -vga virtio -display gtk -drive file=/insilications/build/custom-apps/VirtualBiosMod/OVMF_CODE.fd,if=pflash,format=raw,unit=0,readonly=on -drive file=/insilications/build/custom-apps/VirtualBiosMod/OVMF_VARS.fd,if=pflash,format=raw,unit=1 -serial stdio
# /insilications/build/custom-apps/VirtualBiosMod/tools/uefi-run /insilications/build/custom-apps/VirtualBiosMod/VirtualBiosMod.efi --bios /insilications/build/custom-apps/VirtualBiosMod/OVMF.fd,if=pflash,format=raw,unit=1 --qemu qemu-system-x86_64 -- -enable-kvm -smp 6 -cpu host -m 4024 -vga virtio -display gtk -drive file=/insilications/build/custom-apps/VirtualBiosMod/OVMF_CODE.fd,if=pflash,format=raw,unit=0,readonly=on -drive file=/insilications/build/custom-apps/VirtualBiosMod/OVMF_VARS.fd,if=pflash,format=raw,unit=1 -serial stdio
# /insilications/build/custom-apps/VirtualBiosMod/tools/uefi-run /insilications/build/custom-apps/VirtualBiosMod/VirtualBiosMod.efi --qemu qemu-system-x86_64 -- -enable-kvm -smp 6 -cpu host -m 4024 -vga virtio -display gtk -drive file=/insilications/build/custom-apps/VirtualBiosMod/OVMF.fd,if=pflash,format=raw,unit=0,readonly=on -drive file=/insilications/build/custom-apps/VirtualBiosMod/OVMF_VARS.fd,if=pflash,format=raw,unit=1 -serial stdio
# /insilications/build/custom-apps/VirtualBiosMod/tools/uefi-run /insilications/build/custom-apps/VirtualBiosMod/VirtualBiosMod.efi --qemu qemu-system-x86_64 -- -enable-kvm -smp 6 -cpu host -m 4024 -vga virtio -display gtk -bios /insilications/build/custom-apps/VirtualBiosMod/OVMF.fd -serial stdio -net none
# /usr/bin/uefi-run /insilications/build/custom-apps/VirtualBiosMod/VirtualBiosMod.efi --size 50 --bios /insilications/build/custom-apps/VirtualBiosMod/OVMF.fd --qemu qemu-system-x86_64 -- -enable-kvm -smp 6 -cpu host -m 4024 -vga virtio -display gtk -drive file=/insilications/build/custom-apps/VirtualBiosMod/OVMF_CODE.fd,if=pflash,format=raw,unit=0,readonly=on -drive file=/insilications/build/custom-apps/VirtualBiosMod/OVMF_VARS.fd,if=pflash,format=raw,unit=1 -global driver=cfi.pflash01,property=secure,value=on -serial stdio

# /usr/bin/uefi-run /insilications/build/custom-apps/VirtualBiosMod/VirtualBiosMod.efi --size 50 --qemu qemu-system-x86_64 -- -enable-kvm -smp 8 -cpu host -m 4G -display gtk -drive if=pflash,format=raw,file=/insilications/build/custom-apps/VirtualBiosMod/ovmf.fd -global isa-debugcon.iobase=0x402 -debugcon file:vb.ovmf.log -serial stdio -machine type=q35,accel=kvm -device bochs-display
/usr/bin/uefi-run /insilications/build/custom-apps/VirtualBiosMod/VirtualBiosMod.efi --size 50 --qemu qemu-system-x86_64 -- -machine type=q35,accel=kvm -enable-kvm -smp 8 -cpu host -m 4G -vga virtio -display gtk -global isa-debugcon.iobase=0x402 -debugcon file:vb.ovmf.log -drive file=/insilications/build/custom-apps/VirtualBiosMod/DEBUGX64_OVMF_CODE.fd,if=pflash,format=raw,unit=0,readonly=on -drive file=/insilications/build/custom-apps/VirtualBiosMod/DEBUGX64_OVMF_VARS.fd,if=pflash,format=raw,unit=1 -serial stdio

#  -- -enable-kvm -smp 6 -cpu host -m 4024 -vga virtio -display gtk -serial stdio -net none
# /usr/bin/uefi-run /insilications/build/custom-apps/VirtualBiosMod/VirtualBiosMod.efi --qemu qemu-system-x86_64 --bios /insilications/build/custom-apps/VirtualBiosMod/OVMF.fd
# qemu-system-x86_64 -hda fat:rw:/insilications/build/custom-apps/VirtualBiosMod/hd -drive file=/insilications/build/custom-apps/VirtualBiosMod/OVMF.fd,if=pflash,format=raw,unit=0,readonly=on -drive file=/insilications/build/custom-apps/VirtualBiosMod/OVMF_VARS.fd,if=pflash,format=raw,unit=1 -net none
